sudo: required
services:
  - docker

before_install:
  - docker build -t yatinqss/frontend-travis -f Dockerfile.dev .

scripts:
  - docker run -e CI=true yatinqss/frontend-travis npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-676086224103"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"